language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - source set_env.sh

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed curtarnolds/udagram-api-feed
  - docker tag udagram-api-user curtarnolds/udagram-api-user
  - docker tag udagram-api-frontend curtarnolds/udagram-api-frontend
  - docker tag reverseproxy curtarnolds/reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker
# username and password as below enables you to programmatically log in without
# having the password exposed in logs.
after_success:
d  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push curtarnolds/udagram-api-feed
  - docker push curtarnolds/udagram-api-user
  - docker push curtarnolds/udagram-api-frontend
  - docker push curtarnolds/reverseproxy
